[advisories]
version = 2
ignore = []

[licenses]
version = 2
allow = ["Apache-2.0", "MIT", "BSD-3-Clause", "Unicode-DFS-2016", "ISC"]
confidence-threshold = 0.8

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
